FROM luckyjing/ubuntu
MAINTAINER luckyjing <luckyjing915@163.com>
ENV REFRESHED_AT 2016-12-13

VOLUME ["/usr/share/nginx/html"]

WORKDIR /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["nginx"]
CMD ["-g","daemon off;"]
